name: CI

on:
  push:
  workflow_dispatch:

jobs:
  tests:
    name: "crypto-lib: ${{ matrix.use-crypto-lib }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        use-crypto-lib: ["cryptography", "pycryptodome", "none"]
    steps:
    - name: Update APT packages
      run:
        sudo apt-get update
    - name: Install APT dependencies
      run:
        sudo apt-get install ghostscript
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        repository: 'py-pdf/pypdf'
        submodules: 'recursive'
    - name: Cache Downloaded Files
      id: cache-downloaded-files
      uses: actions/cache@v4
      with:
        path: '**/tests/pdf_cache/*'
        key: cache-downloaded-files
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install requirements (Python 3)
      run: |
        pip install -r requirements/ci-3.11.in
    - name: Remove pycryptodome and cryptography
      run: |
        pip uninstall pycryptodome cryptography -y
    - name: Install cryptography
      run: |
        pip install cryptography
      if: matrix.use-crypto-lib == 'cryptography'
    - name: Install pycryptodome
      run: |
        pip install pycryptodome
      if: matrix.use-crypto-lib == 'pycryptodome'
    - name: Install pypdf
      run: |
        pip install .
    - name: Prepare
      run: |
        python -c "from tests import download_test_pdfs; download_test_pdfs()"
    - name: Test with pytest
      run: |
        python -m pytest tests --cov=pypdf --cov-append -n auto -vv

  codestyle:
    name: Check code style issues
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        repository: 'py-pdf/pypdf'
        submodules: 'recursive'
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install requirements
      run: |
        pip install -r requirements/ci-3.11.in
    - name: Install pypdf
      run: |
        pip install .
    - name: Test with ruff
      run: |
        ruff --version
        ruff .
    - name: Test with mypy
      run : |
        mypy pypdf
    - name: Test docs build
      run: |
        pip install -r requirements/docs.in
        sphinx-build -n -W --keep-going -T -b html docs build/sphinx/html
